/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundingSourcesIndexRouteImport } from './routes/funding-sources/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingSourcesIndexRoute = FundingSourcesIndexRouteImport.update({
  id: '/funding-sources/',
  path: '/funding-sources/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funding-sources': typeof FundingSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funding-sources': typeof FundingSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funding-sources/': typeof FundingSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/funding-sources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/funding-sources'
  id: '__root__' | '/' | '/funding-sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundingSourcesIndexRoute: typeof FundingSourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding-sources/': {
      id: '/funding-sources/'
      path: '/funding-sources'
      fullPath: '/funding-sources'
      preLoaderRoute: typeof FundingSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundingSourcesIndexRoute: FundingSourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
